import org.jetbrains.kotlin.gradle.ExperimentalWasmDsl

plugins {
    alias(libs.plugins.kotlin.multiplatform)
    alias(libs.plugins.kotlin.compose)
    alias(libs.plugins.kotlin.serialization)
    alias(libs.plugins.compose.multiplatform)
    alias(libs.plugins.android.kmp.library)
}

/**
 * Writes the text of source files into a Kotlin file. The game shows the code of a node when its
 * tile is pressed, and reads it from there, so what it shows is always the code that runs.
 */
abstract class EmbedSources : DefaultTask() {
    @get:InputFiles
    @get:PathSensitive(PathSensitivity.NAME_ONLY)
    abstract val sources: ConfigurableFileCollection

    @get:OutputDirectory
    abstract val output: DirectoryProperty

    @TaskAction
    fun write() {
        val entries = sources.files.sortedBy { it.name }.joinToString("\n") { file ->
            val text = file.readText().replace("\r", "")
            val literal = text.replace("\\", "\\\\").replace("\"", "\\\"").replace("$", "\\$").replace("\n", "\\n")
            "    \"${file.name}\" to \"$literal\","
        }
        val file = output.get().asFile.resolve("dev/deeptelar/telar/demo/game/StageSources.kt")
        file.parentFile.mkdirs()
        file.writeText(
            "package dev.deeptelar.telar.demo.game\n\n" +
                "/** The source files of the stage graphs, by file name. Generated by the build; do not edit. */\n" +
                "internal val stageSources: Map<String, String> = mapOf(\n$entries\n)\n",
        )
    }
}

val embedStageSources by tasks.registering(EmbedSources::class) {
    sources.from(
        "src/commonMain/kotlin/dev/deeptelar/telar/demo/game/HelpDesks.kt",
        "src/commonMain/kotlin/dev/deeptelar/telar/demo/game/Agent.kt",
    )
    output.set(layout.buildDirectory.dir("generated/stageSources"))
}

kotlin {
    jvmToolchain(17)

    jvm()

    android {
        namespace = "dev.deeptelar.telar.demo.shared"
        compileSdk = 37
        minSdk = 24
        // The fonts are Compose resources. An Android library only packages resources when asked to.
        androidResources {
            enable = true
        }
    }

    @OptIn(ExperimentalWasmDsl::class)
    wasmJs {
        outputModuleName = "composeApp"
        browser {
            commonWebpackConfig {
                outputFileName = "composeApp.js"
            }
            testTask {
                useKarma {
                    useChromeHeadless()
                }
            }
        }
        binaries.executable()
    }

    applyDefaultHierarchyTemplate()

    sourceSets {
        // The desktop and Android both store their data in files, so they share the code that does it.
        val jvmAndAndroidMain = create("jvmAndAndroidMain") {
            dependsOn(commonMain.get())
        }
        jvmMain.get().dependsOn(jvmAndAndroidMain)
        androidMain.get().dependsOn(jvmAndAndroidMain)
        jvmAndAndroidMain.dependencies {
            implementation(libs.telar.checkpoint.file)
        }

        commonMain {
            kotlin.srcDir(embedStageSources.flatMap { it.output })
        }
        commonMain.dependencies {
            implementation(libs.telar.core)
            implementation(libs.telar.serialization)
            implementation(libs.telar.agent)
            implementation(libs.telar.anthropic)
            implementation(libs.telar.openai)
            implementation(libs.compose.runtime)
            implementation(libs.compose.foundation)
            implementation(libs.compose.ui)
            implementation(libs.compose.animation)
            implementation(libs.compose.resources)
            implementation(libs.kotlinx.coroutines.core)
            implementation(libs.kotlinx.serialization.json)
            implementation(libs.ktor.client.core)
        }
        commonTest.dependencies {
            implementation(kotlin("test"))
            implementation(libs.kotlinx.coroutines.test)
            implementation(libs.ktor.client.mock)
        }
        jvmMain.dependencies {
            implementation(compose.desktop.currentOs)
            implementation(libs.kotlinx.coroutines.swing)
            implementation(libs.ktor.client.cio)
        }
        jvmTest.dependencies {
            implementation(libs.compose.ui.test)
        }
        androidMain.dependencies {
            implementation(libs.ktor.client.okhttp)
        }
        wasmJsMain.dependencies {
            implementation(libs.telar.checkpoint.browser)
            implementation(libs.ktor.client.js)
        }
    }
}

compose.resources {
    packageOfResClass = "dev.deeptelar.telar.demo.resources"
}

compose.desktop {
    application {
        mainClass = "dev.deeptelar.telar.demo.MainKt"
    }
}
